image_sources:
  - name: Front Door
    input_type: generic_usb
    options:
      zoom:
        digital: 1.5
  - name: Conference Room
    input_type: rtsp
    id:
      rtsp_url: rtsp://admin:password@10.0.0.0/cam/realmonitor?channel=1&subtype=0
    options:
      crop:
        relative:
          top: .1
          bottom: .9
          left: .1
          right: .9
  - name: Workshop
    input_type: basler
    id:
      serial_number: 12345678
    options:
      basler:
        ExposureTime: 60000
  - name: International Space Station
    input_type: youtube_live
    id:
      youtube_url: https://www.youtube.com/watch?v=xAieE-QtOeM
