# Auto assign random reviewers to Dependabot PRs
name: auto-assign

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
  workflow_dispatch:

jobs:
  assign-pr-reviewer:
    # Only run this on Dependabot PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout code
    - uses: uesteibar/reviewer-lottery@v3
      name: randomly assign reviewer
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
